// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_items.sql

package database

import (
	"context"
	"encoding/json"
)

const upsertItem = `-- name: UpsertItem :one
INSERT INTO items (task_id, url, platform, data, in_stock)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (task_id, url) DO UPDATE SET in_stock = EXCLUDED.in_stock, data = EXCLUDED.data
RETURNING id, task_id, url, platform, created_at, data, delisted, in_stock
`

type UpsertItemParams struct {
	TaskID   int32           `json:"task_id"`
	Url      string          `json:"url"`
	Platform string          `json:"platform"`
	Data     json.RawMessage `json:"data"`
	InStock  bool            `json:"in_stock"`
}

func (q *Queries) UpsertItem(ctx context.Context, arg UpsertItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, upsertItem,
		arg.TaskID,
		arg.Url,
		arg.Platform,
		arg.Data,
		arg.InStock,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Url,
		&i.Platform,
		&i.CreatedAt,
		&i.Data,
		&i.Delisted,
		&i.InStock,
	)
	return i, err
}
