// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_task_runs.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const getCompletedTaskRuns = `-- name: GetCompletedTaskRuns :many
SELECT id, task_id, started_at, completed_at, status, error_message, status_code, response_time_ms, cache_status FROM task_runs
WHERE status = 'completed' AND task_id = $1
`

func (q *Queries) GetCompletedTaskRuns(ctx context.Context, taskID int32) ([]TaskRun, error) {
	rows, err := q.db.QueryContext(ctx, getCompletedTaskRuns, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskRun
	for rows.Next() {
		var i TaskRun
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Status,
			&i.ErrorMessage,
			&i.StatusCode,
			&i.ResponseTimeMs,
			&i.CacheStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentTaskRuns = `-- name: GetRecentTaskRuns :many
SELECT
  tr.id, tr.started_at, tr.completed_at, tr.status, tr.error_message,
  t.platform, t.url, tr.task_id,
  EXTRACT(EPOCH FROM (tr.completed_at - tr.started_at))::float AS duration_seconds,
  tr.status_code, tr.response_time_ms, tr.cache_status
FROM task_runs tr
JOIN tasks t ON t.id = tr.task_id
WHERE tr.status IN ('completed', 'error')
  AND ($1::text IS NULL OR t.platform = $1)
  AND ($2::text IS NULL OR tr.status = $2)
  AND ($3::int IS NULL OR tr.task_id = $3)
  AND ($4::timestamptz IS NULL OR tr.completed_at < $4)
ORDER BY tr.completed_at DESC NULLS LAST
LIMIT $5
`

type GetRecentTaskRunsParams struct {
	Platform     sql.NullString `json:"platform"`
	FilterStatus sql.NullString `json:"filter_status"`
	TaskID       sql.NullInt32  `json:"task_id"`
	Cursor       sql.NullTime   `json:"cursor"`
	PageLimit    int32          `json:"page_limit"`
}

type GetRecentTaskRunsRow struct {
	ID              int32          `json:"id"`
	StartedAt       time.Time      `json:"started_at"`
	CompletedAt     sql.NullTime   `json:"completed_at"`
	Status          string         `json:"status"`
	ErrorMessage    sql.NullString `json:"error_message"`
	Platform        string         `json:"platform"`
	Url             string         `json:"url"`
	TaskID          int32          `json:"task_id"`
	DurationSeconds float64        `json:"duration_seconds"`
	StatusCode      sql.NullInt32  `json:"status_code"`
	ResponseTimeMs  sql.NullInt32  `json:"response_time_ms"`
	CacheStatus     sql.NullString `json:"cache_status"`
}

func (q *Queries) GetRecentTaskRuns(ctx context.Context, arg GetRecentTaskRunsParams) ([]GetRecentTaskRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentTaskRuns,
		arg.Platform,
		arg.FilterStatus,
		arg.TaskID,
		arg.Cursor,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentTaskRunsRow
	for rows.Next() {
		var i GetRecentTaskRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Status,
			&i.ErrorMessage,
			&i.Platform,
			&i.Url,
			&i.TaskID,
			&i.DurationSeconds,
			&i.StatusCode,
			&i.ResponseTimeMs,
			&i.CacheStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
