// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_task_runs.sql

package database

import (
	"context"
)

const getCompletedTaskRuns = `-- name: GetCompletedTaskRuns :many
SELECT id, task_id, started_at, completed_at, status, error_message FROM task_runs
WHERE status = 'completed' AND task_id = $1
`

func (q *Queries) GetCompletedTaskRuns(ctx context.Context, taskID int32) ([]TaskRun, error) {
	rows, err := q.db.QueryContext(ctx, getCompletedTaskRuns, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskRun
	for rows.Next() {
		var i TaskRun
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Status,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
