// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package database

import (
	"context"
	"encoding/json"
)

const getActiveItemURLsByTask = `-- name: GetActiveItemURLsByTask :many
SELECT id, url FROM items
WHERE task_id = $1 AND delisted = false
`

type GetActiveItemURLsByTaskRow struct {
	ID  int32  `json:"id"`
	Url string `json:"url"`
}

func (q *Queries) GetActiveItemURLsByTask(ctx context.Context, taskID int32) ([]GetActiveItemURLsByTaskRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveItemURLsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveItemURLsByTaskRow
	for rows.Next() {
		var i GetActiveItemURLsByTaskRow
		if err := rows.Scan(&i.ID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveItemsByTask = `-- name: GetActiveItemsByTask :many
SELECT id, task_id, url, platform, created_at, data, delisted, in_stock FROM items
WHERE task_id = $1 AND delisted = false
`

func (q *Queries) GetActiveItemsByTask(ctx context.Context, taskID int32) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getActiveItemsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Url,
			&i.Platform,
			&i.CreatedAt,
			&i.Data,
			&i.Delisted,
			&i.InStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemByTaskAndURL = `-- name: GetItemByTaskAndURL :one
SELECT id, task_id, url, platform, created_at, data, delisted, in_stock FROM items
WHERE task_id = $1 AND url = $2
LIMIT 1
`

type GetItemByTaskAndURLParams struct {
	TaskID int32  `json:"task_id"`
	Url    string `json:"url"`
}

func (q *Queries) GetItemByTaskAndURL(ctx context.Context, arg GetItemByTaskAndURLParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByTaskAndURL, arg.TaskID, arg.Url)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Url,
		&i.Platform,
		&i.CreatedAt,
		&i.Data,
		&i.Delisted,
		&i.InStock,
	)
	return i, err
}

const getItemDataByID = `-- name: GetItemDataByID :one
SELECT data FROM items
WHERE id = $1
`

func (q *Queries) GetItemDataByID(ctx context.Context, id int32) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getItemDataByID, id)
	var data json.RawMessage
	err := row.Scan(&data)
	return data, err
}

const insertItemEvent = `-- name: InsertItemEvent :one
INSERT INTO item_events (item_id, previous_state, new_state)
VALUES ($1, $2, $3)
RETURNING id, item_id, created_at, previous_state, new_state, webhook_sent
`

type InsertItemEventParams struct {
	ItemID        int32           `json:"item_id"`
	PreviousState json.RawMessage `json:"previous_state"`
	NewState      json.RawMessage `json:"new_state"`
}

func (q *Queries) InsertItemEvent(ctx context.Context, arg InsertItemEventParams) (ItemEvent, error) {
	row := q.db.QueryRowContext(ctx, insertItemEvent, arg.ItemID, arg.PreviousState, arg.NewState)
	var i ItemEvent
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.CreatedAt,
		&i.PreviousState,
		&i.NewState,
		&i.WebhookSent,
	)
	return i, err
}

const markItemDelisted = `-- name: MarkItemDelisted :exec
UPDATE items
SET delisted = true
WHERE id = $1
`

func (q *Queries) MarkItemDelisted(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, markItemDelisted, id)
	return err
}

const undelistItem = `-- name: UndelistItem :exec
UPDATE items
SET delisted = false
WHERE id = $1
`

func (q *Queries) UndelistItem(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, undelistItem, id)
	return err
}

const updateItemData = `-- name: UpdateItemData :exec
UPDATE items
SET data = $2
WHERE id = $1
`

type UpdateItemDataParams struct {
	ID   int32           `json:"id"`
	Data json.RawMessage `json:"data"`
}

func (q *Queries) UpdateItemData(ctx context.Context, arg UpdateItemDataParams) error {
	_, err := q.db.ExecContext(ctx, updateItemData, arg.ID, arg.Data)
	return err
}

const updateItemInStock = `-- name: UpdateItemInStock :exec
UPDATE items
SET in_stock = $2
WHERE id = $1
`

type UpdateItemInStockParams struct {
	ID      int32 `json:"id"`
	InStock bool  `json:"in_stock"`
}

func (q *Queries) UpdateItemInStock(ctx context.Context, arg UpdateItemInStockParams) error {
	_, err := q.db.ExecContext(ctx, updateItemInStock, arg.ID, arg.InStock)
	return err
}
