// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"
)

type DiscordUser struct {
	ID            int32     `json:"id"`
	DiscordUserID string    `json:"discord_user_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type Item struct {
	ID        int32           `json:"id"`
	TaskID    int32           `json:"task_id"`
	Url       string          `json:"url"`
	Platform  string          `json:"platform"`
	CreatedAt time.Time       `json:"created_at"`
	Data      json.RawMessage `json:"data"`
	Delisted  bool            `json:"delisted"`
	InStock   bool            `json:"in_stock"`
}

type ItemEvent struct {
	ID            int32           `json:"id"`
	ItemID        int32           `json:"item_id"`
	CreatedAt     time.Time       `json:"created_at"`
	PreviousState json.RawMessage `json:"previous_state"`
	NewState      json.RawMessage `json:"new_state"`
	WebhookSent   bool            `json:"webhook_sent"`
}

type Proxy struct {
	ID          int32          `json:"id"`
	ProxyListID int32          `json:"proxy_list_id"`
	Host        string         `json:"host"`
	Port        string         `json:"port"`
	Username    sql.NullString `json:"username"`
	Password    sql.NullString `json:"password"`
	CreatedAt   time.Time      `json:"created_at"`
}

type ProxyList struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Task struct {
	ID          int32         `json:"id"`
	Platform    string        `json:"platform"`
	TaskType    string        `json:"task_type"`
	Url         string        `json:"url"`
	ProxyListID sql.NullInt32 `json:"proxy_list_id"`
	Delay       int32         `json:"delay"`
	Enabled     bool          `json:"enabled"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
	ChannelID   string        `json:"channel_id"`
}

type TaskRun struct {
	ID           int32          `json:"id"`
	TaskID       int32          `json:"task_id"`
	StartedAt    time.Time      `json:"started_at"`
	CompletedAt  sql.NullTime   `json:"completed_at"`
	Status       string         `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
}
