// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: proxies.sql

package database

import (
	"context"
)

const getProxiesByListID = `-- name: GetProxiesByListID :many
SELECT id, proxy_list_id, host, port, username, password, created_at FROM proxies
WHERE proxy_list_id = $1
`

func (q *Queries) GetProxiesByListID(ctx context.Context, proxyListID int32) ([]Proxy, error) {
	rows, err := q.db.QueryContext(ctx, getProxiesByListID, proxyListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Proxy
	for rows.Next() {
		var i Proxy
		if err := rows.Scan(
			&i.ID,
			&i.ProxyListID,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.Password,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
