// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: servers.sql

package database

import (
	"context"
)

const createUserServer = `-- name: CreateUserServer :one
INSERT INTO user_servers (discord_user_id, guild_id, guild_name)
VALUES ($1, $2, $3)
ON CONFLICT (discord_user_id, guild_id)
DO UPDATE SET guild_name = EXCLUDED.guild_name
RETURNING id, discord_user_id, guild_id, guild_name, created_at
`

type CreateUserServerParams struct {
	DiscordUserID int32  `json:"discord_user_id"`
	GuildID       string `json:"guild_id"`
	GuildName     string `json:"guild_name"`
}

func (q *Queries) CreateUserServer(ctx context.Context, arg CreateUserServerParams) (UserServer, error) {
	row := q.db.QueryRowContext(ctx, createUserServer, arg.DiscordUserID, arg.GuildID, arg.GuildName)
	var i UserServer
	err := row.Scan(
		&i.ID,
		&i.DiscordUserID,
		&i.GuildID,
		&i.GuildName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserServer = `-- name: DeleteUserServer :exec
DELETE FROM user_servers WHERE id = $1 AND discord_user_id = $2
`

type DeleteUserServerParams struct {
	ID            int32 `json:"id"`
	DiscordUserID int32 `json:"discord_user_id"`
}

func (q *Queries) DeleteUserServer(ctx context.Context, arg DeleteUserServerParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserServer, arg.ID, arg.DiscordUserID)
	return err
}

const getUserServerByGuildID = `-- name: GetUserServerByGuildID :one
SELECT id, discord_user_id, guild_id, guild_name, created_at FROM user_servers WHERE discord_user_id = $1 AND guild_id = $2
`

type GetUserServerByGuildIDParams struct {
	DiscordUserID int32  `json:"discord_user_id"`
	GuildID       string `json:"guild_id"`
}

func (q *Queries) GetUserServerByGuildID(ctx context.Context, arg GetUserServerByGuildIDParams) (UserServer, error) {
	row := q.db.QueryRowContext(ctx, getUserServerByGuildID, arg.DiscordUserID, arg.GuildID)
	var i UserServer
	err := row.Scan(
		&i.ID,
		&i.DiscordUserID,
		&i.GuildID,
		&i.GuildName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserServers = `-- name: GetUserServers :many
SELECT id, discord_user_id, guild_id, guild_name, created_at FROM user_servers WHERE discord_user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetUserServers(ctx context.Context, discordUserID int32) ([]UserServer, error) {
	rows, err := q.db.QueryContext(ctx, getUserServers, discordUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserServer
	for rows.Next() {
		var i UserServer
		if err := rows.Scan(
			&i.ID,
			&i.DiscordUserID,
			&i.GuildID,
			&i.GuildName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
