// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createProductSubscription = `-- name: CreateProductSubscription :one
INSERT INTO task_subscriptions (task_id, channel_id, mode, item_id, guild_id)
VALUES ($1, $2, 'restock', $3, $4)
ON CONFLICT (task_id, channel_id, item_id) WHERE mode = 'restock'
DO NOTHING
RETURNING id, task_id, channel_id, mode, item_id, created_at, guild_id
`

type CreateProductSubscriptionParams struct {
	TaskID    int32          `json:"task_id"`
	ChannelID string         `json:"channel_id"`
	ItemID    sql.NullInt32  `json:"item_id"`
	GuildID   sql.NullString `json:"guild_id"`
}

func (q *Queries) CreateProductSubscription(ctx context.Context, arg CreateProductSubscriptionParams) (TaskSubscription, error) {
	row := q.db.QueryRowContext(ctx, createProductSubscription,
		arg.TaskID,
		arg.ChannelID,
		arg.ItemID,
		arg.GuildID,
	)
	var i TaskSubscription
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ChannelID,
		&i.Mode,
		&i.ItemID,
		&i.CreatedAt,
		&i.GuildID,
	)
	return i, err
}

const createStoreSubscription = `-- name: CreateStoreSubscription :one
INSERT INTO task_subscriptions (task_id, channel_id, mode, guild_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (task_id, channel_id) WHERE mode IN ('all', 'new')
DO UPDATE SET mode = EXCLUDED.mode, guild_id = EXCLUDED.guild_id
RETURNING id, task_id, channel_id, mode, item_id, created_at, guild_id
`

type CreateStoreSubscriptionParams struct {
	TaskID    int32          `json:"task_id"`
	ChannelID string         `json:"channel_id"`
	Mode      string         `json:"mode"`
	GuildID   sql.NullString `json:"guild_id"`
}

func (q *Queries) CreateStoreSubscription(ctx context.Context, arg CreateStoreSubscriptionParams) (TaskSubscription, error) {
	row := q.db.QueryRowContext(ctx, createStoreSubscription,
		arg.TaskID,
		arg.ChannelID,
		arg.Mode,
		arg.GuildID,
	)
	var i TaskSubscription
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ChannelID,
		&i.Mode,
		&i.ItemID,
		&i.CreatedAt,
		&i.GuildID,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM task_subscriptions WHERE id = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteSubscription, id)
	return err
}

const getSubscriptionsByChannel = `-- name: GetSubscriptionsByChannel :many
SELECT id, task_id, channel_id, mode, item_id, created_at, guild_id FROM task_subscriptions WHERE channel_id = $1
`

func (q *Queries) GetSubscriptionsByChannel(ctx context.Context, channelID string) ([]TaskSubscription, error) {
	rows, err := q.db.QueryContext(ctx, getSubscriptionsByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskSubscription
	for rows.Next() {
		var i TaskSubscription
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ChannelID,
			&i.Mode,
			&i.ItemID,
			&i.CreatedAt,
			&i.GuildID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionsByGuildIDs = `-- name: GetSubscriptionsByGuildIDs :many
SELECT id, task_id, channel_id, mode, item_id, created_at, guild_id FROM task_subscriptions WHERE guild_id = ANY($1::text[])
`

func (q *Queries) GetSubscriptionsByGuildIDs(ctx context.Context, dollar_1 []string) ([]TaskSubscription, error) {
	rows, err := q.db.QueryContext(ctx, getSubscriptionsByGuildIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskSubscription
	for rows.Next() {
		var i TaskSubscription
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ChannelID,
			&i.Mode,
			&i.ItemID,
			&i.CreatedAt,
			&i.GuildID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionsByTask = `-- name: GetSubscriptionsByTask :many
SELECT id, task_id, channel_id, mode, item_id, created_at, guild_id FROM task_subscriptions WHERE task_id = $1
`

func (q *Queries) GetSubscriptionsByTask(ctx context.Context, taskID int32) ([]TaskSubscription, error) {
	rows, err := q.db.QueryContext(ctx, getSubscriptionsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskSubscription
	for rows.Next() {
		var i TaskSubscription
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ChannelID,
			&i.Mode,
			&i.ItemID,
			&i.CreatedAt,
			&i.GuildID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
