// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package database

import (
	"context"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
  platform, task_type, url, delay
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, platform, task_type, url, webhook_id, proxy_list_id, delay, enabled, created_at, updated_at
`

type CreateTaskParams struct {
	Platform string `json:"platform"`
	TaskType string `json:"task_type"`
	Url      string `json:"url"`
	Delay    int32  `json:"delay"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Platform,
		arg.TaskType,
		arg.Url,
		arg.Delay,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.TaskType,
		&i.Url,
		&i.WebhookID,
		&i.ProxyListID,
		&i.Delay,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, platform, task_type, url, webhook_id, proxy_list_id, delay, enabled, created_at, updated_at FROM tasks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id int32) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.TaskType,
		&i.Url,
		&i.WebhookID,
		&i.ProxyListID,
		&i.Delay,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTasks = `-- name: GetTasks :many
SELECT id, platform, task_type, url, webhook_id, proxy_list_id, delay, enabled, created_at, updated_at FROM tasks
ORDER BY created_at DESC
`

func (q *Queries) GetTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.TaskType,
			&i.Url,
			&i.WebhookID,
			&i.ProxyListID,
			&i.Delay,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
