// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_runs.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const deleteTaskRunsBefore = `-- name: DeleteTaskRunsBefore :execrows
DELETE FROM task_runs
WHERE id IN (
  SELECT tr.id FROM task_runs tr WHERE tr.completed_at < $1 LIMIT $2
)
`

type DeleteTaskRunsBeforeParams struct {
	CompletedAt sql.NullTime `json:"completed_at"`
	Limit       int32        `json:"limit"`
}

func (q *Queries) DeleteTaskRunsBefore(ctx context.Context, arg DeleteTaskRunsBeforeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTaskRunsBefore, arg.CompletedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertCompletedTaskRun = `-- name: InsertCompletedTaskRun :exec
INSERT INTO task_runs (task_id, started_at, completed_at, status, error_message, status_code, response_time_ms, cache_status)
VALUES ($1, $2, NOW(), $3, $4, $5, $6, $7)
`

type InsertCompletedTaskRunParams struct {
	TaskID         int32          `json:"task_id"`
	StartedAt      time.Time      `json:"started_at"`
	Status         string         `json:"status"`
	ErrorMessage   sql.NullString `json:"error_message"`
	StatusCode     sql.NullInt16  `json:"status_code"`
	ResponseTimeMs sql.NullInt32  `json:"response_time_ms"`
	CacheStatus    sql.NullString `json:"cache_status"`
}

func (q *Queries) InsertCompletedTaskRun(ctx context.Context, arg InsertCompletedTaskRunParams) error {
	_, err := q.db.ExecContext(ctx, insertCompletedTaskRun,
		arg.TaskID,
		arg.StartedAt,
		arg.Status,
		arg.ErrorMessage,
		arg.StatusCode,
		arg.ResponseTimeMs,
		arg.CacheStatus,
	)
	return err
}
