// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
)

const getDiscordUserByDiscordID = `-- name: GetDiscordUserByDiscordID :one
SELECT id, discord_user_id, created_at, username, avatar, access_token, refresh_token, token_expires_at FROM discord_users WHERE discord_user_id = $1
`

func (q *Queries) GetDiscordUserByDiscordID(ctx context.Context, discordUserID string) (DiscordUser, error) {
	row := q.db.QueryRowContext(ctx, getDiscordUserByDiscordID, discordUserID)
	var i DiscordUser
	err := row.Scan(
		&i.ID,
		&i.DiscordUserID,
		&i.CreatedAt,
		&i.Username,
		&i.Avatar,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
	)
	return i, err
}

const getDiscordUserByID = `-- name: GetDiscordUserByID :one
SELECT id, discord_user_id, created_at, username, avatar, access_token, refresh_token, token_expires_at FROM discord_users WHERE id = $1
`

func (q *Queries) GetDiscordUserByID(ctx context.Context, id int32) (DiscordUser, error) {
	row := q.db.QueryRowContext(ctx, getDiscordUserByID, id)
	var i DiscordUser
	err := row.Scan(
		&i.ID,
		&i.DiscordUserID,
		&i.CreatedAt,
		&i.Username,
		&i.Avatar,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
	)
	return i, err
}

const upsertDiscordUser = `-- name: UpsertDiscordUser :one
INSERT INTO discord_users (discord_user_id, username, avatar, access_token, refresh_token, token_expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (discord_user_id)
DO UPDATE SET
  username = EXCLUDED.username,
  avatar = EXCLUDED.avatar,
  access_token = EXCLUDED.access_token,
  refresh_token = EXCLUDED.refresh_token,
  token_expires_at = EXCLUDED.token_expires_at
RETURNING id, discord_user_id, created_at, username, avatar, access_token, refresh_token, token_expires_at
`

type UpsertDiscordUserParams struct {
	DiscordUserID  string       `json:"discord_user_id"`
	Username       string       `json:"username"`
	Avatar         string       `json:"avatar"`
	AccessToken    string       `json:"access_token"`
	RefreshToken   string       `json:"refresh_token"`
	TokenExpiresAt sql.NullTime `json:"token_expires_at"`
}

func (q *Queries) UpsertDiscordUser(ctx context.Context, arg UpsertDiscordUserParams) (DiscordUser, error) {
	row := q.db.QueryRowContext(ctx, upsertDiscordUser,
		arg.DiscordUserID,
		arg.Username,
		arg.Avatar,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	var i DiscordUser
	err := row.Scan(
		&i.ID,
		&i.DiscordUserID,
		&i.CreatedAt,
		&i.Username,
		&i.Avatar,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
	)
	return i, err
}
