DROP TABLE IF EXISTS item_events;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS task_runs;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS discord_users;
DROP TABLE IF EXISTS proxies;
DROP TABLE IF EXISTS proxy_lists;
DROP TABLE IF EXISTS webhooks;
